# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Mad Tadders | Southern WI Live Music
email: madtadders@gmail.com
description: 
  twitter:
  username: 
  social:
  name: 
  links:
    - https://www.facebook.com/MadTadders/
    - https://www.youtube.com/channel/UCps30V-Pj_qGEme7PsUFu7w
github_username:  12oss

# Build settings
markdown:         kramdown
theme:            minima

#Author
author:
  twitter: 

#Teaser Image
image: /assets/css/images/wordmark-sq-600.svg


#Logo
logo: /assets/css/images/wordmark-sq-600.svg

#Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Permalinks
# HELPFUL
#https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#http://coopcoding.com/blog/my-jekyll-setup-for-this-blog/
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      category: "blog"

#html compress
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Server
source:           _gh_pages
destination:      docs
host:             0.0.0.0
port:             12055
baseurl:          "/madtadders"
#Production : https://12oss.github.io/secondcropcreative/
#DEV : http://0.0.0.0:12055/secondcropcreative/
#site.github.url
#site.baseurl
url:              "https://12oss.github.io/madtadders/"
encoding:         UTF-8


# Disqus post comments
disqus_shortname: 


#Compress HTML
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []


# Gems
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
 # - github-pages
 # - jekyll-github-metadata

